# Generated by Django 3.1.1 on 2020-09-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36, unique=True)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('publish_date', models.DateField(blank=True, default=None, null=True)),
                ('Is_Famous', models.BooleanField(default=False)),
                ('Covers', models.ImageField(blank=True, upload_to='covers/')),
            ],
        ),
    ]
